### ISSUE TITLE
Unable to setup github secrets whicha re needed for github actions to run after scaffolding

### ISSUE THREAD

**Issue by samarpan-b** [sourcefuse/backstage#116]
**Describe the bug**
After the microservices repo scaffolding, we need to add docker related secrets to github for github actions to perform docker build and docker push. This is not working because the repo which is created, the creator from Backstage is not admin there by default.

**To Reproduce**
1. Go to 'https://dx.arc-prod.link/catalog'
2. Click on 'Create' and choose ARC microservices template
3. Let it complete and at the end it will generate a repo in sourcefuse org
4. Go to the repo and see that you dont have access to Admin tab

**Expected behavior**
The creatot from Backstage should at least get Admin permission of the repo.

**Screenshots**

**Additional context**

**Comment by Yogi-Vishwas** [comment]
@jamescrowley321 This issue arises because upon scaffolding the template, the repository lacks an admin. Currently, only organization administrators possess admin privileges for repositories.

To resolve this during template scaffolding, we can easily designate a user as an admin of the repository. This can be achieved through adjustments to the template as follows:

1. In the template.yaml file, we introduce a parameter field to capture the GitHub username of the desired admin:

```yaml
  parameters:
    - title: Provide some simple information
      required:
        - component_id
        - admin 
      properties:
        component_id:
          title: Name
          type: string
          description: Unique name of the component
        admin:
          title: Admin of the Repo
          type: string
          description: Github Username 
```

2. Utilizing the collaborators property of the publish:github action, we assign the designated user an admin role:

```yaml
    - id: publish
      name: Publish
      action: publish:github
      input:
        allowedHosts: ["github.com"]
        description: This is ${{ parameters.component_id }}
        repoUrl: ${{ parameters.repoUrl }}
        collaborators:
          - user: ${{ parameters.admin }}
            access: admin
```
